
# Forum descriptor (Forum lib)

parent: publications

fields:
    description:    string
    position:       integer
    parent_id:      ref=0
    post_date:      datetime    # Last date a sub-post or this post was edited/added


indexes:
     - INDEX(user_id)
     - INDEX(parent_id)
     - FULLTEXT(description)
     