
# Entity Test Entities descriptor (FAKE)

parent: publications

fields:
    slug: string(4, 20) 


indexes:
     - INDEX(user_id)
     - UNIQUE(name)
     - FULLTEXT(slug, cache)=mySlugIndex
     