
# File descriptor

fields:
    # Header
    create_date:            datetime=sqlDatetime()
    create_ip:              ip=clientIP()
    create_user_id:         ref=userID()
    
    # Identification
    name:                   string(200)                 # Nom visuel du fichier
    extension:              string(5)                   # Extension locale
    mimetype:               string(100)                 # Type MIME
    usage:                  enum(listFileUsages)        # Usage
    parent_id:              ref=0                       # Document
    position:               natural=0                   # Position dans son référentiel
    passkey:                string(30)                  # Download key
    
    # Source
    source_type:            enum(listFileSourceTypes)   # Type de source
    source_name:            string(200)=                # Nom du fichier utilisé par la source
    source_url:             url[nullable]               # Url
    
indexes:
    - INDEX(usage)
