
# Forum Post descriptor (Forum lib)

parent: publications

fields:
    message:        string
    forum_id:       ref
    parent_id:      ref=0
    post_date:      datetime[nullable]  # Last date a post of the forum was edited/added
    last_answer_id: ref=0               # The ID of the last answer
    type:           enum(ForumPost::getTypes())   # The type of post


indexes:
     - INDEX(user_id)
     - FULLTEXT(message)
     