
# User descriptor

# Maybe it could define if validation is strict

fields:
    a_number: number(0, 0, 255)
    a_string: string()
    a_string2: string(20)
    an_integer: integer(0, 255)
    a_date: date(FR)
    a_datetime: datetime(FR)
    an_email: email()
    a_password: password()
    a_phone: phone(FR)
    an_url: url()
    an_ip: ip()
    an_url: url()
    a_ref: ref()
    an_enum: enum(getEnumValues)
#    name:
#        type: string(6,50)
#        validator: is_name
#    password:
#        type: password
#    accesslevel:
#        type: integer
#        max: 999
#    status:
#        type: code
#        source: User::checkStatus
#    email:
#        type: email
#        max: 999
#    email_public:
#        type: email
#        max: 999


# 'id' 'name' 'password' 'accesslevel', 'status', 'email', 'email_public'
# 'create_time', 'create_ip', 'activation_time', 'activation_ip',
#'login_time', 'login_ip', 'activity_time', 'activity_ip'    

indexes: []
