# 
# Usage:
# Route Access Type > Route > Route Config
# 
# This YAML configuration file is made to work with package orpheus/orpheus-inputcontroller
# 
# HTTP Route allows the following config:
# - path : The relative path to this route. Mandatory config.
# - method : Restrict path access to the given HTTP method.
# - controller : The controller to use to process this route
# - restrictTo : Restriction configuration for this route, you can customize accessibility, the common field is "role".
# - redirect : Redirect to the given URL, using RedirectController.
# - url_config : Redirect to the URL provided by the configurable url_config, using RedirectController & AppConfig. Require orpheus/orpheus-webtools.
# - render : The template to render this route, using StaticPageController. Processed as option.
# Other fields will be send as options to the controller, controller can access to all this configuration.
#
# Known roles: visitor, member, moderator, administrator, developer
# Unspecified role does not restrict access, "visitor" restricts to not-logged user only.
#
# Examples :
#    home:
#        path: "/path/in/array/config"
#        method: "POST|GET"
#        method: "GET"
#        controller: "HomeController"
#    home2: "/path/with/all/methods->HomeController"
#    home3: "POST(/path/for/POST/method)->HomeController"

http:
    home:
        path: "/"
        controller: "HomeController"
        
    user_login:
        path: "/user_login.html"
        controller: "UserLoginController"
        restrictTo:
          role: visitor
          
    logout:
        path: "/logout.html"
        controller: "LogoutController"
        restrictTo:
          role: member
        
    admin_demo:
        path: "/admin/home.html"
        controller: "AdminDemoController"
        restrictTo:
          role: member
        
    adm_mysettings:
        path: "/admin/my_settings.html"
        controller: "AdminMySettingsController"
        restrictTo:
          role: member
        
    adm_users:
        path: "/admin/users.html"
        controller: "AdminUserListController"
        restrictTo:
          role: administrator
        
    adm_user:
        path: "/admin/user/{id:userID}.html"
        controller: "AdminUserEditController"
        restrictTo:
          role: administrator
        
    adm_config:
        path: "/admin/config.html"
        controller: "AdminConfigController"
        restrictTo:
          role: developer
        
    dev_entities:
        path: "/admin/dev_entities.html"
        controller: "DevEntitiesController"
        restrictTo:
          role: developer
        
    dev_composer:
        path: "/developer/composer.html"
        controller: "ComposerController"
        
    file_download:
        path: "/download/{id:fileID}"
        controller: "FileDownloadController"
        
    setup_start:
        path: "/setup/"
        controller: "StartSetupController"
        
    setup_checkfs:
        path: "/setup/check-filesystem.html"
        controller: "CheckFileSystemSetupController"
        
    setup_checkdb:
        path: "/setup/check-database.html"
        controller: "CheckDatabaseSetupController"
        
    setup_installdb:
        path: "/setup/install-database.html"
        controller: "InstallDatabaseSetupController"
        
    setup_installfixtures:
        path: "/setup/install-fixtures.html"
        controller: "InstallFixturesSetupController"
        
    setup_end:
        path: "/setup/finish.html"
        controller: "EndSetupController"
