
# Usage:
# Route Access Type > Route > Route Config
#
# HTTP Route allows the following config:
# - path : The relative path to this route. Mandatory config.
# - method : Restrict path access to the given HTTP method.
# - controller : The controller to use to process this route
# - restrictTo : Restriction configuration for this route, you can customize accessibility, the common field is "role".
# - render : The template to render this route, using StaticPageController. Processed as option.
# Other fields will be send as options to the controller, controller can access to all this configuration.
#
# Roles: visitor, member, moderator, administrator, developer
# Unspecified role does not restrict access, "visitor" restricts to not-logged user only.

http:
    home:
        path: "/"
        controller: "HomeController"
        
    user_login:
        path: "/user_login.html"
        controller: "UserLoginController"
        
#    sample_twig:
#        path: "/sample_twig.html"
#        controller: "TwigSampleController"
        
    thread:
        path: "/thread.html"
        controller: "ThreadController"
        
    download:
        path: "/download.html"
        controller: "DownloadController"
        
    faq:
        path: "/faq.html"
        render: "app/faq"
        
    admin_demo:
        path: "/admin/home.html"
        controller: "AdminDemoController"
        restrictTo:
          role: member
        
    adm_mysettings:
        path: "/admin/my_settings.html"
        controller: "AdminMySettingsController"
        restrictTo:
          role: member
        
    adm_users:
        path: "/admin/users.html"
        controller: "AdminUserListController"
        restrictTo:
          role: administrator
        
    adm_user:
        path: "/admin/user/{id:userID}.html"
        controller: "AdminUserEditController"
        restrictTo:
          role: administrator
        
    adm_config:
        path: "/admin/config.html"
        controller: "AdminConfigController"
        restrictTo:
          role: administrator
        
    dev_entities:
        path: "/admin/dev_entities.html"
        controller: "DevEntitiesController"
        restrictTo:
          role: developer
          
    logout:
        path: "/logout.html"
        controller: "LogoutController"
        restrictTo:
          role: member
        
    file_download:
        path: "/download/{id:fileID}"
        controller: "FileDownloadController"
        
#    home:
#        path: "/path/in/array/config"
#        method: "POST|GET"
#        method: "GET"
#        controller: "HomeController"
#    home2: "/path/with/all/methods->HomeController"
#    home3: "POST(/path/for/POST/method)->HomeController"
    
