

http:
    home:
        path: "/"
        controller: "HomeController"
    user_login:
        path: "/user_login.html"
        controller: "UserLoginController"
    sample_twig:
        path: "/sample_twig.html"
        controller: "TwigSampleController"
    admin_demo:
        path: "/admin_demo.html"
        controller: "AdminDemoController"
    thread:
        path: "/thread.html"
        controller: "ThreadController"
    faq:
        path: "/faq.html"
        render: "app/faq"
        
#    home:
#        path: "/path/in/array/config"
#        method: "POST|GET"
#        method: "GET"
#        controller: "HomeController"
#    home2: "/path/with/all/methods->HomeController"
#    home3: "POST(/path/for/POST/method)->HomeController"
    
